# Generated by Django 4.1.4 on 2022-12-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('uuid', models.JSONField(verbose_name='uuid')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('school_id', models.CharField(max_length=10, verbose_name='school id')),
                ('course', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=5)),
                ('random', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.JSONField(verbose_name='uuid')),
                ('date_time', models.DateTimeField(verbose_name='date & time')),
                ('course', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=5)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
