# Generated by Django 4.1.4 on 2022-12-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_student_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='excused',
            field=models.BooleanField(default=False),
        ),
    ]
